<%@ Page Language="C#" MasterPageFile="~/AdminModule/MasterPageAdmin.Master" AutoEventWireup="true" CodeFile="GroupList.aspx.cs" Inherits="DemoWebsite.AdminModule.GroupList" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:GridView Width="100%" ID="GridView1" runat="server" AllowPaging="True" DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="True">
        <PagerSettings Mode="NumericFirstLast" />
    
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectDB %>"
        SelectCommand="SELECT Id,[Tên]= Name,[SL Con]= mt24gio.CountGroupChild(Id), ParentGroupItemId, mt24gio.CountItem(Id) AS [Số lượng sp] FROM GroupItem WHERE (ParentGroupItemId = 0)"></asp:SqlDataSource>
</asp:Content>
